[package]
name = "rcl"
version = "0.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
unicode-width = "0.1.10"

[profile.release]
lto = "thin"
panic = "abort"
strip = true

[workspace]
members = ["pyrcl"]
