site_name: RCL
site_url: https://docs.ruuda.nl/rcl
repo_url: https://github.com/ruuda/rcl
strict: true

theme:
  name: null
  custom_dir: docs/theme

markdown_extensions:
  - codehilite
  - footnotes
  - toc:
      permalink: true
      permalink_title: null

nav:
  - "Overview": "index.md"
  - "User guide":
      - "Installation": "installation.md"
      - "Syntax highlighting": "syntax_highlighting.md"
  - "Language guide":
      - "Syntax": "syntax.md"
      - "Strings": "strings.md"
      - "Null": "null.md"
      - "Imports": "imports.md"
      - "Glossary": "glossary.md"
  - "Reference":
      - "rcl": "rcl.md"
      - "rcl evaluate": "rcl_evaluate.md"
      - "rcl format": "rcl_format.md"
      - "rcl highlight": "rcl_highlight.md"
      - "rcl query": "rcl_query.md"
  - "Development":
      - "Testing": "testing.md"
