[package]
name = "rcl-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1.3.0"
libfuzzer-sys = "0.4"

[dependencies.rcl]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "cli"
path = "fuzz_targets/cli.rs"
test = false
doc = false

[[bin]]
name = "escapes"
path = "fuzz_targets/escapes.rs"
test = false
doc = false

[[bin]]
name = "is_identifier"
path = "fuzz_targets/is_identifier.rs"
test = false
doc = false

[[bin]]
name = "main"
path = "fuzz_targets/main.rs"
test = false
doc = false

[[bin]]
name = "string_len"
path = "fuzz_targets/string_len.rs"
test = false
doc = false
